### ISSUE TITLE
Ability to export word timings

### ISSUE THREAD

**Issue by rehandaphedar** [zonetecde/QuranCaption#2]
السَّلاَمُ عَلَيْكُمْ وَرَحْمَةُ اللهِ وَبَرَكَاتُهُ

It would be great, after using the asset manager and subtitle editor, to have an option to export the word timings.

For example, let's say I load Sūrah Nās and add subtitles. A sample export could look like this:
```json
{
    "114:1:1": {
        "start": 0.1,
        "end": 0.35
    },
    "114:1:2": {
        "start": 0.35,
        "end": 0.53
    },
    "114:1:3": {
        "start": 0.53,
        "end": 0.84
    },
    "114:1:4": {
        "start": 0.84,
        "end": 1.1
    },
    "114:1:5": {
        "start": 1.1,
        "end": 1.28
    }
}
```

Here, `114:1:2` refers to `Chapter 114; Verse 1; Word 2`. Or, any other suitable export format would work.

The numbering of the words could either be standardised (For example, by using https://api-docs.quran.com's word numbering), or, the text of the word could be included in the object, or any similar solution.

**Comment by zonetecde** [comment]
Wa alaykum salam wa rahmatulLah. What about exporting the subtitles as an SRT file or another subtitle format?

This means it will be plain text and not a word index.

Or I can add both. For what purpose would you need this?"

**Comment by zonetecde** [comment]
Feature added in latest version.

[v1.9](https://github.com/zonetecde/QuranCaption-2/releases/tag/v1.9)

**Comment by rehandaphedar** [comment]
Great! This tool seemed very useful to me for generating word timing files for recitations, such as the ones used on https://quran.com.
